### ISSUE TITLE
Meetup Time Format

### ISSUE THREAD

**Issue by Dean-Coakley** [davej/CorkJS#1]
Hi,

I don't understand how to interpret the time data I get back from the api.

For CorkJS #8 it returns: 1484850600000

Side note: I have a good amount working but it's terrible code. Pretty much no js experience. Should be opening a pull request tomorrow. Hopefully you can then point out where I can improve or how things should work.

Thanks.

**Comment by davej** [comment]
Hi Dean,

Awesome stuff. The time date that comes back is a [unix epoch](https://en.wikipedia.org/wiki/Unix_time) (in milliseconds). You can convert it to a [JS date object](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date) using:

```js
var date = new Date(1484850600000)
```

You can then call `date.getDate()`, `date.getMonth()` etc...

Small gotcha: Some of these values (e.g.`month`) are zero-indexed, others (e.g. `date`)  are not. You can compare dates using the normal JS comparative operators `>`, `<`, `<=` or `>=`.

I'll open a PR for your existing work now even though it's a WIP and give some feedback. You can just continue working on your fork and it will update the PR.

Thanks for the great work!
