### ISSUE TITLE
TravisCI Linting

### ISSUE THREAD

**Issue by Dean-Coakley** [davej/CorkJS#15]
So continuing on from travis ci linting you mentioned in https://github.com/davej/CorkJS/pull/14

How would this work? I assume it just run a linter and give a bad test result that you can view if the styling is bad? It would tell you specific line number/problem.

**Comment by davej** [comment]
Yes, add a test script to the `package.json`. Something like shown here: https://github.com/pingyhq/nm-prune/blob/master/package.json#L17

So, it you wanted to use eslint then it would look like:
```json
  "scripts": {
    "test": "eslint ."
  },
```

Assuming [eslint is set-up and working](https://eslint.org/docs/user-guide/getting-started) (you can use `npm test` to run it) then it would just be a case of adding a `.travis.yml` file, something like this: https://github.com/pingyhq/nm-prune/blob/master/.travis.yml

That particular file would cause `npm test` to be run on node versions 6,8 and 9. Travis will then report on all future PRs to make sure that they pass.


More info on setting up eslint: https://eslint.org/docs/user-guide/getting-started
There are also various linters for html and css if you wanted to try them. Let me know if run into any issues.
