### ISSUE TITLE
New meetup returns strange link from api

### ISSUE THREAD

**Issue by Dean-Coakley** [davej/CorkJS#4]
Api returns:
`check out &lt;a&gt;<a href=\"https://cork.js.org/&lt;/a&gt\"`

Which results on:
`check out <a>https://cork.js.org/</a>;. `
Being outputted to front end. (Visible on live site.)

I can change it to return plain text from api but looks poor with absolutely no formatting. Do you just need to make sure the link is formatted in some way (Looks like it's a link in a link at the moment) on the event? Or do I have to parse out excessive html using some js or something.

Also: Code style looks great now. Sorry about the poor style, I always use tabs/4 spaces and it was hard for me to adapt. Never considered 80 char limit but it seems to make a big difference.

**Comment by davej** [comment]
No, I think it's just an issue with the description, nothing to do with your code. I'll try and debug it later.

**Comment by davej** [comment]
Fixed by editing meetup description
